name: Deploy with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/EventTicketing

            git pull origin main

            docker stop event-container || true
            docker rm event-container || true

            docker build -t event-app .

            docker run -d -p 8080:8080 --env-file .env --name event-container event-app
